repos:
- repo: https://github.com/dj-wasabi/pre-commit-hooks
  rev: 0.1.0
  hooks:
  - id: helm-lint
  # - id: helm-unittest
  - id: markdown-toc

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: check-json
    - id: check-merge-conflict
    - id: detect-private-key
    - id: check-added-large-files
    - id: check-case-conflict
    - id: end-of-file-fixer
