# Default values for helm-zabbix.

image:
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: www.example.com
      secretName: www.example.com
      paths:
        - "/"
  # tls:
  #   - hosts:
  #     - www.example.com
  #     secretName: www.example.com

zabbix:
  version: 5.0-latest
  database:
    type: mysql
    name: zabbix
    host: mysql-8.default.svc.cluster.local

server:
  enabled: true
  database: {}

  javagateway:
    enable: true
    javapollers: 5

  snmptraps:
    enabled: true
  externalIPs: []
  env: {}

web:
  enabled: true
  timezone: Europe/Riga

agent:
  enabled: true
  securityContext:
    privileged: true
    runAsUser: 1997
  server:
    host: ""
  timeout: 10
  startagents: 3
  passiveagent: true
  volumes_host: true
  volumes: []
  volumeMounts: []
