# Default values for helm-zabbix.

image:
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  annotations: {}
  hosts:
  - host: www.example.com
    secretName: www.example.com
    paths:
    - /
  # tls:
  #   - hosts:
  #     - www.example.com
  #     secretName: www.example.com

zabbix:
  version: 6.4-latest
  database:
    type: mysql
    name: zabbix
    host: mysql.default.svc.cluster.local
  namespace: zabbix
  networkPolicy:
    enabled: true

server:
  enabled: true
  database: {}
  securityContext:
    privileged: true
    runAsUser: 1997

  snmptraps:
    enabled: true
  externalIPs: []
  env: {}
  volumes: []
  volumeMounts: []
  tolerations: []
  readinessProbe:
    tcpSocket:
      port: zabbix-trapper
    initialDelaySeconds: 5
    periodSeconds: 10
  livenessProbe:
    tcpSocket:
      port: zabbix-trapper
    initialDelaySeconds: 15
    periodSeconds: 10
  startupProbe:
    tcpSocket:
      port: zabbix-trapper
    failureThreshold: 30
    periodSeconds: 10

web:
  enabled: true
  webserver: nginx
  timezone: Europe/Riga
  securityContext:
    privileged: true
    runAsUser: 1997
  env: {}
  tolerations: []
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 400Mi
  livenessProbe:
    httpGet:
      path: /
      port: web-http
      scheme: HTTP
    initialDelaySeconds: 15
    timeoutSeconds: 2
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /
      port: web-http
      scheme: HTTP
    initialDelaySeconds: 15
    timeoutSeconds: 2
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 5


agent:
  enabled: true
  securityContext:
    privileged: true
    runAsUser: 1997
  server:
    host: ''
  env: {}
  tolerations: []
  timeout: 10
  startagents: 3
  passiveagent: true
  volumes_host: true
  volumes: []
  volumeMounts: []
