apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ .Values.zabbix.namespace }}"
  labels:
    {{- include "helm-zabbix.labels" . | nindent 4 }}
  name: zabbix-server
data:
  {{- if .Values.server.env }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.server.env "context" $ ) | nindent 2 }}
  {{- end }}
