{{- if and .Values.zabbix.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zabbix-web
  namespace: "{{ .Values.zabbix.namespace }}"
spec:
  podSelector:
    matchLabels:
      app: zabbix-web
  ingress:
  - {}
  egress:
  - {}
{{- end }}
