{{- if and .Values.server.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "zabbix-server"
  labels:
    app: zabbix
    {{- include "helm-zabbix.labels" . | nindent 4 }}
  namespace: zabbix
spec:
  clusterIP: None
  ports:
  - port: 10051
    targetPort: 10051
    protocol: TCP
    name: "zabbix-trapper"
  {{- if .Values.server.snmptraps.enabled }}
  - port: 162
    targetPort: 1162
    protocol: UDP
    name: "snmp-trap"
  {{- end }}
  selector:
    app: "zabbix-server"
{{- if .Values.server.externalIPs }}
  externalIPs:
  {{- toYaml .Values.server.externalIPs | nindent 8 }}
{{- end }}
{{- end }}