apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web-http
  - port: 443
    targetPort: 8443
    name: web-https
  selector:
    app: zabbix-web
