# This will execute some scripts on main branch.

name: MasterRun

on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  runme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout dj-wasabi-release repo
        uses: actions/checkout@v2
        with:
          repository: dj-wasabi/dj-wasabi-release
          path: /tmp/dj-wasabi-release

      - name: Commit Changelog file
        run: |
          /tmp/dj-wasabi-release/release.sh -d
          git config --global user.name "Werner Dijkerman [GH bot]"
          git config --global user.email "github@dj-wasabi.nl"

          git add CHANGELOG.md
          git commit -m "Updated CHANGELOG on \"$(date "+%Y-%m-%d %H:%M:%S")\"" CHANGELOG.md
          git push
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
