# This will execute some scripts on main branch.

name: MasterRun

on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  runme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dj-wasabi-release repo
        uses: actions/checkout@v2
        with:
          repository: dj-wasabi/dj-wasabi-release
          path: dj-wasabi-release

      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Commit Changelog file
        run: main/.github/update-changelog.sh
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
