# This will execute some scripts on main branch.

name: MasterRun

on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  runme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout dj-wasabi-release repo
        uses: actions/checkout@v2
        with:
          repository: dj-wasabi/dj-wasabi-release
          path: dj-wasabi-release

      - name: Commit Changelog file
        run: |
          cd main
          ../dj-wasabi-release/release.sh -d
          git status
          if [[ $(git status | grep modified | wc -l) -ge 1 ]]
            then  echo "Committing file"
                  git config --global user.name 'Werner Dijkerman [GH bot]'
                  git config --global user.email 'github@dj-wasabi.nl'

                  git add CHANGELOG.md
                  git commit -m "Updated CHANGELOG" CHANGELOG.md
                  # git push
          fi
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
